# Generated by Django 5.2.8 on 2025-11-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Empleado activo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='lunch_end_time',
            field=models.TimeField(blank=True, help_text='Fin de hora de comida', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lunch_start_time',
            field=models.TimeField(blank=True, help_text='Inicio de hora de comida', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Hora de salida', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Hora de entrada', null=True),
        ),
    ]
