# Generated by Django 5.2.8 on 2025-11-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employee_password_employee_role_employee_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, help_text='Departamento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Título del puesto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor directo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='attendance.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CEO', 'CEO'), ('DIRECTOR', 'Director'), ('MANAGER', 'Gerente'), ('OPERATOR', 'Operador'), ('EMPLOYEE', 'Empleado')], default='EMPLOYEE', max_length=20),
        ),
    ]
