# Generated by Django 6.0.4 on 2026-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_department_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Permisos globales del sistema'),
        ),
    ]
